### ISSUE TITLE
Unhandled exception through docker

### ISSUE THREAD

**Issue by nithou** [uilton-oliveira/sonarr_scanner#19] opened 2022-01-31 16:16 UTC
Hey !

Thanks a lot for this script, it's exactly what I'm looking for :) However when I'm trying to run it through Docker on my Synology, I encounter the problem below (logs), any idea what I could do to fix it?

Thanks a lot : )

```
   Unhandled exception. Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at sonarr_scanner.Monitor.Scan() in /source/src/Monitor.cs:line 187
   at sonarr_scanner.Monitor.<Init>b__5_3() in /source/src/Monitor.cs:line 113
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by uilton-oliveira** [comment] 2022-01-31 16:38
@nithou hi, have you configured the docker volume correctly? looks like it can't read the config file, you have to create a folder where it will be stored, use the sample in readme and fill it correctly, then map the volume to the file you created, like in the readme

**Comment by nithou** [comment] 2022-01-31 16:59
Yes I mapped the settings files correctly, and it connects to both installation of Sonarr and Radarr but just stops at the middle of the road

**Comment by nithou** [comment] 2022-01-31 17:07
It's strange because it seems to go through all the Sonarr tv shows but crash just after Westworld for an unknow reason

**Comment by uilton-oliveira** [comment] 2022-01-31 17:28
That's strange, the line it's failing is just a simple log.. maybe it's some character in the show name that is causing the problem, but not sure... mind to share the full log?

**Comment by nithou** [comment] 2022-01-31 18:45
No problem ! Here it goes :) 

[full-logs.zip](https://github.com/uilton-oliveira/sonarr_scanner/files/7973320/full-logs.zip)

**Comment by uilton-oliveira** [comment] 2022-01-31 19:11
It looks like the problem is with Sonarr, thay dropped the support for legacy API, that was being used... i'll update it to use the new api

**Comment by uilton-oliveira** [comment] 2022-01-31 21:29
@nithou try pulling the image again, should be fixed now.

**Comment by nithou** [comment] 2022-02-01 07:35
Gonna try this ! I pull it through https://registry.hub.docker.com/ so gonna have to wait for it to propagate! Thanks for the update you rock : )

**Comment by nithou** [comment] 2022-02-01 19:02
It works like a charm now! Thanks a lot! 🙏🏻🙏🏻🙏🏻🔥

**Comment by uilton-oliveira** [comment] 2022-02-01 19:04
nice :)

**Closed by uilton-oliveira** 2022-02-01 19:04 UTC
